# Generated by Django 5.1.6 on 2025-03-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupant_name', models.CharField(blank=True, max_length=20, null=True)),
                ('room_number', models.IntegerField(unique=True)),
                ('bed_type', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Queen', 'Queen'), ('King', 'King')], max_length=10)),
                ('smoking', models.CharField(max_length=5)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
